/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Administrator
 */
public class NewJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();
        setSize(600,720);
    }
 public NewJFrame2(String s ){
     this();
     tv.setText(s);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tv = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Mainmenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        tv.setFont(new java.awt.Font("Trebuchet MS", 3, 48)); // NOI18N
        tv.setForeground(new java.awt.Color(255, 51, 51));
        tv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tv.setText("Red Car");
        tv.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel3.add(tv);
        tv.setBounds(10, 20, 580, 70);

        Exit.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 24)); // NOI18N
        Exit.setText("Exit");
        Exit.setToolTipText("");
        Exit.setActionCommand(" Bottom Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel3.add(Exit);
        Exit.setBounds(160, 480, 260, 40);

        Mainmenu.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 24)); // NOI18N
        Mainmenu.setText("Main Menu");
        Mainmenu.setActionCommand(" Bottom main menu");
        Mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainmenuActionPerformed(evt);
            }
        });
        jPanel3.add(Mainmenu);
        Mainmenu.setBounds(160, 260, 260, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pngtree-vector-car-race-png-image_3170136.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 720);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 600, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainmenuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new NewJFrame().setVisible(true);
    }//GEN-LAST:event_MainmenuActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
                
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Mainmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel tv;
    // End of variables declaration//GEN-END:variables
}
